### ISSUE TITLE
Does not work with if input file name contains spaces.

### ISSUE THREAD

**Issue by efegurkan** [technopagan/sqip#12]
To reproduce:
`squip ./file\ with\ spaces.png`

It is most likely an issue with `primitive` itself or when we pass the filename to the primitive since process throws error from primitive package.

**Comment by sido420** [comment]
updates on this issue?

**Comment by efegurkan** [comment]
I tried it locally it should be also fixed with `0.3.1`. 

Please feel free to reopen if you encounter it again.
