### ISSUE TITLE
win32 installation problems

### ISSUE THREAD

**Issue by mbalabash** [technopagan/sqip#15]
Hello. Firstly i want to say thanks for your work.
Today i tried to install sqip on my laptop with windows 10. And found few problems:
1) child_process.execSync('type primitive') works incorrect for me (in checkForPrimitive function). 
2) process.env.PWD return undefined (in getInputfilePath function).

I fix that issues and create pull request (#14). Now all work good for me.
Please, check my solution. Maybe i do something wrong.
Thanks.

**Comment by technopagan** [comment]
@mbalabash Thank you so much for the Pull Request (https://github.com/technopagan/sqip/pull/14) that fixes this issue! Awesome! 👍
