### ISSUE TITLE
Not blurring all images.

### ISSUE THREAD

**Issue by jowy** [technopagan/sqip#17]
When running a batch of images, a small selection of SVGs will not actually get blurred. The SVG's that don't get blurred may actually get blurred on the next batch and visa versa.

![Screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/2x2A3C37022b1X3T0645/Screen%20Shot%202017-11-15%20at%208.04.40%20PM%20copy.png)

SVG Content:
```
data:image/svg xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 750 937'><path fill='#5e5145' d='M0 0h750v937H0z'/><path fill='#ffceae' fill-opacity='.5' d='M455.7 108l7.3 600.2L31.1 561.8z'/><ellipse fill-opacity='.5' rx='1' ry='1' transform='matrix(95.1777 101.02218 -375.52495 353.79954 302.3 76.1)'/><path fill='#fff1cf' fill-opacity='.5' d='M441 979l113.5-292.7L357 752.2z'/><ellipse fill='#00110b' fill-opacity='.5' rx='1' ry='1' transform='matrix(-118.08246 -24.86798 90.92995 -431.76942 634.4 845.2)'/><ellipse fill-opacity='.5' rx='1' ry='1' transform='matrix(-56.65586 45.16032 -103.38974 -129.70753 285.9 891.6)'/><path fill='#370000' fill-opacity='.5' d='M287.3 518h73.2v245h-73.2z'/><path fill='#fffff2' fill-opacity='.5' d='M130 543.5l164.6 172L258 499.7z'/><path fill='#baf8ff' fill-opacity='.5' d='M629 289.5l-2.5-73.2 124.3-4.3 2.6 73.1z'/><ellipse fill='#000002' fill-opacity='.5' rx='1' ry='1' transform='matrix(-125.36617 -5.50313 3.40138 -77.48636 645.6 36)'/><path fill='#001109' fill-opacity='.5' d='M382.6 434.2l33.7-60.8 134.5 74.5-33.8 60.8z'/></svg>
```

**Comment by sylvaindumont** [comment]
It's due to #1, if you find a way to improve the regex to add a top level g element when missing, image will be correctly blurred.
If you use the image on a website you can disable the blur in svg
```javascript
// remove filter to apply it in css
const svgAttr = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${
  sqiped.img_dimensions.width
} ${sqiped.img_dimensions.height}">`;
const filter = `<filter id="b"><feGaussianBlur stdDeviation="12" /></filter>`;
const transform = `<g filter="url(#b)"`;
svg = svg.replace(`${svgAttr}${filter}`, svgAttr);
if (!svg.match(transform)) {
  svg = svg.replace(transform, '<g');
}
```
and apply it in css
```css
.blur {
  filter: blur(12px);
 }
```
But if you find a way to fix this regex https://github.com/technopagan/sqip/blob/master/src/index.js#L115 and submit a pr it would be much better

**Comment by jowy** [comment]
Thanks, I will look in to the regex today.

**Comment by jowy** [comment]
Opened PR #19 for review.

You will want to probably calculate the scale attributes correctly for the `<g>` element. Due to time I am not able to do this. However, testing with 200+ images seems to work perfectly fine.
