### ISSUE TITLE
Node library without CLI

### ISSUE THREAD

**Issue by Munter** [technopagan/sqip#4]
In order to ease imlementation in other tools it would be helpful to expose a node library separate from the command line tool.

**Comment by fxck** [comment]
how about a webpack plugin / loader?

**Comment by Munter** [comment]
A webpack loader starts with a node runnable library. Anyone can pick up the webpack plugin part after that

**Comment by efegurkan** [comment]
This tool depends heavily on `primitive` which is written in golang which can be very limiting for the node API. It is still doable though.

**Comment by technopagan** [comment]
@efegurkan's Pull Request https://github.com/technopagan/sqip/pull/13 (now merged) should fix this. 🎉
