### ISSUE TITLE
SQIP generation blocks Node

### ISSUE THREAD

**Issue by bdrtsk** [technopagan/sqip#46]
I absolutely love this package, but I can't solve a huge problem with it.

It completly blocks my server while processing the image!
I was hoping to fix this by using separate job (using Bull queue) but no success. Whole server stops and doesn't respond to requests when this job is started. Job is started in separate thread, but still SQIP completely blocks everything!

How do I handle this? Please help me guys, really want to use this is production.

UPD: after all I managed to process SQIP in separate process. Now it doesn't block server.

**Comment by axe312ger** [comment]
will be fixed with #5  and #42
