### ISSUE TITLE
Try to fix SVG output when using the polygon option in Primitive 

### ISSUE THREAD

**Issue by technopagan** [technopagan/sqip#9]
Currently, the polygon mode in Primitive cannot export to SVG. SVGs created by it are empty. See https://github.com/fogleman/primitive/issues/44 for reference. 

Once we've ported Primitive to JS (https://github.com/technopagan/sqip/issues/6), we can investigate fixing the polygon SVG export. Polygons might help us achieve higher similarity with fewer bytes in SVG.

**Comment by linkerlin** [comment]
see PR #55

**Comment by denisbrodbeck** [comment]
This has been merged in commit [69506c9](https://github.com/fogleman/primitive/commit/69506c928bef740cc2b04cc385d878083556b206).

**Comment by axe312ger** [comment]
Jup, this is fixed :)
